#!/bin/sh

mypath="`echo $0 | sed -e 's,[^/]*$,,;s,/$,,;s,^$,.,'`"
cd ${mypath}
mypath=$PWD

${mypath}/../../hook-scripts/update-setup
if [ -e "${HOME}/.gitconfig" ]; then
  ${mypath}/../../hook-scripts/setup-gitconfig "${HOME}/.gitconfig"
fi



