#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }

mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"

case "${USER}" in
    'jschewe')
        git config --global user.email 'jschewe@bbn.com'
        ;;
    'jpschewe')
        git config --global user.email 'jpschewe@mtu.net'
        ;;
esac

# push nothing, always use explicit
git config --global push.default tracking

# turn on colors
git config --global color.branch 'auto'
git config --global color.diff 'auto'
git config --global color.status 'auto'
git config --global color.ui 'auto'

# aliases
git config --global alias.nlog 'log --date=relative --abbrev-commit --graph'
git config --global alias.redocommit 'reset --soft HEAD^'
git config --global alias.diffemptytreehash 'diff -p 4b825dc642cb6eb9a060e54bf8d69288fbee4904'

# turn on rerere to keep track of conflict resolutions
git config --global rerere.enabled true
