#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }

mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"

auto=0
while getopts a?h opt
do	case "${opt}" in
	a)	auto=1;;
	[?] | h)	fatal "Usage: ${0} [-a]";;
	esac
done
shift $((OPTIND-1))


# get git submodules
git submodule update --init

# setup hook scripts
ln -sf "${mydir}/hook-scripts/post-applypatch" "${mydir}/.git/hooks/post-applypatch"
ln -sf "${mydir}/hook-scripts/post-applypatch" "${mydir}/.git/hooks/post-commit"
ln -sf "${mydir}/hook-scripts/post-applypatch" "${mydir}/.git/hooks/post-merge"

# setup bin
mkdir -p "${HOME}/bin"
for script in musicbox; do
  ln -sf "${mydir}/${script}" "${HOME}/bin/${script}"
done
ln -sf "${mydir}/lib/vcprompt/bin/vcprompt" "${HOME}/bin/vcprompt"

# bash
ln -sf "${mydir}/addpath" "${HOME}/.addpath"
ln -sf "${mydir}/bash_profile" "${HOME}/.bash_profile"
ln -sf "${mydir}/bash_logout" "${HOME}/.bash_logout"
ln -sf "${mydir}/bashrc" "${HOME}/.bashrc"
ln -sf "${mydir}/packages" "${HOME}/.packages"

# vim
ln -sf "${mydir}/vimrc" "${HOME}/.vimrc"
if [ -L "${HOME}/.vim" ]; then
  rm -f "${HOME}/.vim"
  ln -sf "${mydir}/vim" "${HOME}/.vim"
elif [ -f "${HOME}/.vim" ]; then
  if [ ${auto} -eq 0 ]; then
    log "Expecting ${HOME}/.vim to be a symlink or a directory, not a file, skipping"
  fi
elif [ -d "${HOME}/.vim" ]; then
  if [ ${auto} -eq 0 ]; then
    log "${HOME}/.vim already exists as a directory, moving to the side"
  fi
  mv "${HOME}/.vim" "${HOME}/.vim.old"
  ln -sf "${mydir}/vim" "${HOME}/.vim"
else
  ln -sf "${mydir}/vim" "${HOME}/.vim"
fi

# screen
ln -sf "${mydir}/screenrc" "${HOME}/.screenrc"

# subversion
mkdir -p "${HOME}/.subversion"
if [ -f "${HOME}/.subversion/config" ]; then
  /bin/mv "${HOME}/.subversion/config" "${HOME}/.subversion/config.old"
fi
ln -fs "${mydir}/subversion-config" "${HOME}/.subversion/config"

# cvs
ln -fs "${mydir}/cvsrc" "${HOME}/.cvsrc"

# git
ln -fs "${mydir}/global-gitignore" "${HOME}/.global-gitignore"

if [ ${auto} -eq 0 ]; then
  # ask about ssh
  printf "Would you like to have ssh-agent start up on login? (y/N) "
  answer=''
  read answer
  if [ "x${answer}" = "xy" ]; then
    mkdir -p "${HOME}/.ssh"
    ln -sf "${mydir}/sssha" "${HOME}/.ssh/sssha"
    ln -sf "${mydir}/sssha-helper" "${HOME}/.ssh/sssha-helper"
  else
    rm -f "${HOME}/.ssh/sssha"
    rm -f "${HOME}/.ssh/sssha-helper"
  fi
fi

# setup bash-it - https://github.com/revans/bash-it
if [ -L "${HOME}/.bash_it" ]; then
    rm -f "${HOME}/.bash_it"
    ln -s "${mydir}/lib/bash-it" "${HOME}/.bash_it"
elif [ -f "${HOME}/.bash_it" ]; then
  if [ ${auto} -eq 0 ]; then
    log "Expecting ${HOME}/.bash_it to be a symlink or a directory, not a file, skipping"
  fi
elif [ -d "${HOME}/.bash_it" ]; then
  if [ ${auto} -eq 0 ]; then
    log "${HOME}/.bash_it already exists as a directory, moving to the side"
  fi
  mv "${HOME}/.bash_it" "${HOME}/.bash_it.old"
  ln -s "${mydir}/lib/bash-it" "${HOME}/.bash_it"
else
  ln -s "${mydir}/lib/bash-it" "${HOME}/.bash_it"
fi
