#!/bin/bash
# Hey EMACS, this should be in -*- sh -*- mode

if [ $OSTYPE = "cygwin" ]; then
  keychain_cache=`ipconfig /all | egrep "Physical Address" | awk '{print $NF}' | head -1`
elif [ -x /sbin/ifconfig ]; then
  # find the first ethernet card's MAC address as this is unique to a machine.
  # Make sure to grep out vmware server interfaces 
  keychain_cache=`/sbin/ifconfig -a | egrep '(ether|HWaddr)' | awk '{print $NF}' | egrep -iv '^00:50:56' | head -1`
elif [ -n "${HOSTNAME}" ]; then
  keychain_cache=${HOSTNAME}
else
  keychain_cache="unknown-host"  
fi

if [ -n "`type -p keychain`" ]; then
  if [ $EMACS ]; then
    keychain="keychain --host ${keychain_cache} --nocolor"
  else
    if test -t 0; then
      keychain="keychain --host ${keychain_cache} -q"
    else
      keychain="keychain --host ${keychain_cache}"
    fi
  fi
  
  if [ -f ${HOME}/.ssh/id_dsa ]; then
    ${keychain} id_dsa
  fi
  if [ -f ${HOME}/.ssh/id_rsa ]; then
    ${keychain} id_rsa
  fi
  if [ -f $HOME/.keychain/${keychain_cache}-sh ]; then
    source $HOME/.keychain/${keychain_cache}-sh
  fi
  if [ -f $HOME/.keychain/${keychain_cache}-sh-gpg ]; then
    source  $HOME/.keychain/${keychain_cache}-sh-gpg
  fi
fi
