#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }

mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"

# get git submodules
# Run a second time if there is an error. This happens when a new submodule is added.
git submodule sync >/dev/null
git submodule update --init >/dev/null || git submodule update --init >/dev/null
